CREATE DATABASE country ENCODING 'UTF8';

\connect country;

CREATE TABLE IF NOT EXISTS country
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS requested_country
(
    id SERIAL PRIMARY KEY,
    country_id BIGINT NOT NULL,
    distance_to_buenos_aires BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS country_name_ix ON country USING btree (name);

CREATE MATERIALIZED VIEW country_stats AS
SELECT 1 as id, *
FROM
(
    SELECT c.name AS min_distance_country, rc.distance_to_buenos_aires AS min_distance_to_buenos_aires
    FROM country c JOIN requested_country rc ON c.id = rc.country_id
    WHERE rc.distance_to_buenos_aires = (SELECT MIN(distance_to_buenos_aires) FROM requested_country)
    LIMIT 1
) AS min,
(
    SELECT c.name AS max_distance_country, rc.distance_to_buenos_aires AS max_distance_to_buenos_aires
    FROM country c JOIN requested_country rc ON c.id = rc.country_id
    WHERE rc.distance_to_buenos_aires = (SELECT MAX(distance_to_buenos_aires) FROM requested_country)
    LIMIT 1
) AS max,
(
    SELECT AVG(rc.distance_to_buenos_aires) AS avg_distance_to_buenos_aires
    FROM requested_country rc
) AS avg;


INSERT INTO country(name)
VALUES
    ('Afghanistan'),
    ('Sudan'),
    ('Burundi'),
    ('Mexico'),
    ('Cuba'),
    ('Serbia'),
    ('Monaco'),
    ('Bhutan'),
    ('Guyana'),
    ('South Georgia'),
    ('Bosnia and Herzegovina'),
    ('Brunei'),
    ('Pakistan'),
    ('Kenya'),
    ('Puerto Rico'),
    ('Somalia'),
    ('Svalbard and Jan Mayen'),
    ('Sierra Leone'),
    ('French Polynesia'),
    ('Azerbaijan'),
    ('Cook Islands'),
    ('Peru'),
    ('Bouvet Island'),
    ('Northern Mariana Islands'),
    ('Angola'),
    ('Republic of the Congo'),
    ('South Sudan'),
    ('Saint Martin'),
    ('Turkey'),
    ('Anguilla'),
    ('Saint Kitts and Nevis'),
    ('Aruba'),
    ('Turks and Caicos Islands'),
    ('Taiwan'),
    ('Sweden'),
    ('Liberia'),
    ('Venezuela'),
    ('United States Virgin Islands'),
    ('Bermuda'),
    ('Albania'),
    ('Hong Kong'),
    ('Luxembourg'),
    ('Eritrea'),
    ('Colombia'),
    ('Caribbean Netherlands'),
    ('Mongolia'),
    ('Yemen'),
    ('Lebanon'),
    ('Antigua and Barbuda'),
    ('Vietnam'),
    ('Palau'),
    ('Jersey'),
    ('Trinidad and Tobago'),
    ('Israel'),
    ('Bulgaria'),
    ('Portugal'),
    ('Gibraltar'),
    ('San Marino'),
    ('Singapore'),
    ('Sint Maarten'),
    ('Saudi Arabia'),
    ('Ghana'),
    ('Moldova'),
    ('Chad'),
    ('Antarctica'),
    ('United Kingdom'),
    ('Papua New Guinea'),
    ('French Southern and Antarctic Lands'),
    ('United States Minor Outlying Islands'),
    ('Belize'),
    ('Comoros'),
    ('Burkina Faso'),
    ('Faroe Islands'),
    ('Guinea'),
    ('India'),
    ('Curaçao'),
    ('Togo'),
    ('Tunisia'),
    ('Saint Barthélemy'),
    ('Indonesia'),
    ('Micronesia'),
    ('Austria'),
    ('Tajikistan'),
    ('DR Congo'),
    ('Mayotte'),
    ('Réunion'),
    ('Romania'),
    ('Qatar'),
    ('Lithuania'),
    ('China'),
    ('New Zealand'),
    ('Norfolk Island'),
    ('Mauritania'),
    ('Uzbekistan'),
    ('Finland'),
    ('Cameroon'),
    ('Heard Island and McDonald Islands'),
    ('Dominica'),
    ('Iceland'),
    ('Oman'),
    ('North Macedonia'),
    ('Liechtenstein'),
    ('Spain'),
    ('Greece'),
    ('Paraguay'),
    ('Bahrain'),
    ('Niue'),
    ('Senegal'),
    ('Montserrat'),
    ('Latvia'),
    ('Tokelau'),
    ('Japan'),
    ('Central African Republic'),
    ('Gabon'),
    ('Iraq'),
    ('Isle of Man'),
    ('Myanmar'),
    ('Montenegro'),
    ('Nauru'),
    ('Vanuatu'),
    ('France'),
    ('Zimbabwe'),
    ('Philippines'),
    ('Slovakia'),
    ('Australia'),
    ('Ivory Coast'),
    ('British Indian Ocean Territory'),
    ('Eswatini'),
    ('Rwanda'),
    ('Benin'),
    ('British Virgin Islands'),
    ('Uganda'),
    ('Ireland'),
    ('Iran'),
    ('Slovenia'),
    ('Mali'),
    ('Switzerland'),
    ('American Samoa'),
    ('Uruguay'),
    ('Guam'),
    ('Suriname'),
    ('Ukraine'),
    ('Czechia'),
    ('Honduras'),
    ('Samoa'),
    ('Laos'),
    ('Cape Verde'),
    ('Ethiopia'),
    ('Bangladesh'),
    ('Saint Helena, Ascension and Tristan da Cunha'),
    ('Belarus'),
    ('Croatia'),
    ('Kuwait'),
    ('French Guiana'),
    ('Morocco'),
    ('Russia'),
    ('Estonia'),
    ('Sri Lanka'),
    ('New Caledonia'),
    ('Poland'),
    ('Madagascar'),
    ('Costa Rica'),
    ('El Salvador'),
    ('Macau'),
    ('Andorra'),
    ('Italy'),
    ('Namibia'),
    ('Seychelles'),
    ('Panama'),
    ('Haiti'),
    ('Argentina'),
    ('Niger'),
    ('Malawi'),
    ('Pitcairn Islands'),
    ('Germany'),
    ('Kiribati'),
    ('Syria'),
    ('Marshall Islands'),
    ('Hungary'),
    ('Cayman Islands'),
    ('Denmark'),
    ('Saint Lucia'),
    ('Bolivia'),
    ('Djibouti'),
    ('South Africa'),
    ('Nigeria'),
    ('São Tomé and Príncipe'),
    ('Nicaragua'),
    ('Guadeloupe'),
    ('Saint Pierre and Miquelon'),
    ('Ecuador'),
    ('Greenland'),
    ('Grenada'),
    ('Bahamas'),
    ('Chile'),
    ('Malaysia'),
    ('Tuvalu'),
    ('Christmas Island'),
    ('Solomon Islands'),
    ('Tanzania'),
    ('North Korea'),
    ('Guinea-Bissau'),
    ('Kosovo'),
    ('Vatican City'),
    ('Norway'),
    ('Palestine'),
    ('Cocos (Keeling) Islands'),
    ('Jamaica'),
    ('Egypt'),
    ('Cambodia'),
    ('Mauritius'),
    ('Gambia'),
    ('Equatorial Guinea'),
    ('Lesotho'),
    ('Martinique'),
    ('United States'),
    ('Western Sahara'),
    ('United Arab Emirates'),
    ('Mozambique'),
    ('Algeria'),
    ('Zambia'),
    ('Guatemala'),
    ('South Korea'),
    ('Kyrgyzstan'),
    ('Timor-Leste'),
    ('Åland Islands'),
    ('Jordan'),
    ('Malta'),
    ('Cyprus'),
    ('Falkland Islands'),
    ('Kazakhstan'),
    ('Botswana'),
    ('Saint Vincent and the Grenadines'),
    ('Barbados'),
    ('Tonga'),
    ('Thailand'),
    ('Belgium'),
    ('Canada'),
    ('Georgia'),
    ('Wallis and Futuna'),
    ('Fiji'),
    ('Netherlands'),
    ('Armenia'),
    ('Dominican Republic'),
    ('Guernsey'),
    ('Turkmenistan'),
    ('Nepal'),
    ('Maldives'),
    ('Libya'),
    ('Brazil');

