version: '3.4'
services:

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:latest
    user: root
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "./kafka-data:/bitnami"
    environment:
      - BITNAMI_DEBUG=true
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9092,CONTROLLER://:9093,PLAINTEXT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9092,PLAINTEXT://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
    depends_on:
      - kafka

  postgres:
    container_name: "postgresql"
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
       POSTGRES_PASSWORD: "password"
    volumes:
      - "./postgresql-init-scripts:/docker-entrypoint-initdb.d"
      - "./postgresql-data:/var/lib/postgresql/data"

  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/data"
    command: ["redis-server", "--save 60 1"]

  redis-insight:
    container_name: "redis-insight"
    image: "redislabs/redisinsight:latest"
    user: root
    ports:
      - "9001:8001"
    volumes:
      - "./redisinsight-data:/db"
    depends_on:
      - redis

  countries:
    container_name: "countries"
    image: "mercadolibre.rodrigo/countries"
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_REACTIVE_URL=vertx-reactive:postgresql://postgres:5432/country
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
      - QUARKUS_REDIS_HOSTS=redis://redis:6379
      - COUNTRIES_IP_API_API_KEY=private
      - COUNTRIES_COUNTRY_API_API_KEY=private
    depends_on:
      - postgres
      - redis
      - kafka

  stats:
    container_name: "stats"
    image: "mercadolibre.rodrigo/stats"
    ports:
      - "8081:8080"
    environment:
      - QUARKUS_DATASOURCE_REACTIVE_URL=vertx-reactive:postgresql://postgres:5432/country
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
      - STATS_CRON_TIME=30s
    depends_on:
      - postgres
      - kafka